spring:
  application:
    name: TechLab
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION} # 15 minutes in milliseconds

app:
  frontend:
    url: ${FRONTEND_URL}


mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

server:
  port: ${PORT:8080}